packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]

packetbeat.protocols.memcache:
  ports: [11211]

packetbeat.protocols.mysql:
  ports: [3306]

packetbeat.protocols.pgsql:
  ports: [5432]

packetbeat.protocols.redis:
  ports: [6379]

packetbeat.protocols.thrift:
  ports: [9090]

packetbeat.protocols.mongodb:
  ports: [27017]

packetbeat.protocols.cassandra:
  ports: [9042]

processors:
- add_cloud_metadata: ~



setup.dashboards.enabled: true

#============================

setup.kibana:
  host: "https://192.168.1.38:5601"
  username: "elastic"
  password: "elastic"
  ssl.verification_mode: certificate
  ssl.certificate_authorities: /usr/share/packetbeat/config/certs/ca/ca.crt


#=================================

#output.elasticsearch:
 # hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  #username: '${ELASTICSEARCH_USERNAME:}'
  #password: '${ELASTICSEARCH_PASSWORD:}'

#=================================

output.logstash:
  hosts: ["192.168.1.38:5044"]
  ssl.certificate_authorities: ["/usr/share/packetbeat/config/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/packetbeat/config/certs/logstash/logstash.crt"
  ssl.key: "/usr/share/packetbeat/config/certs/logstash/logstash.pkcs8.key"

