metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false
#============================
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
#============================
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

#============================
processors:
  - add_cloud_metadata: ~

#============================


setup.dashboards.enabled: true

#============================

setup.kibana:
  host: "https://192.168.1.38:5601"
 # host: "192.168.1.9:5601"
  username: "elastic"
  password: "elastic"
  ssl.verification_mode: certificate
  ssl.certificate_authorities: /usr/share/metricbeat/config/certs/ca/ca.crt

#======================================

#output.elasticsearch:
  #hosts: '${ELASTICSEARCH_HOSTS:192.168.1.9:9200}'
  #username: '${ELASTICSEARCH_USERNAME:elastic}'
  #password: '${ELASTICSEARCH_PASSWORD:elastic}'

#======================================

output.logstash:
  hosts: ["192.168.1.38:5044"]
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/metricbeat/config/certs/logstash/logstash.crt"
  ssl.key: "/usr/share/metricbeat/config/certs/logstash/logstash.pkcs8.key"
#======================================
